In [1]:
import pandas as pd

In [2]:
import numpy as np


In [5]:
df = pd.read_csv("review_dataset.csv")

In [6]:
df

review label
0      The Buddy Holly Story opens on a shot of a yel...   pos
1      ***SPOILERS*** Like some evil Tinkers-to-Evers...   neg
2      Ghost of Dragstrip Hollow is a typical 1950's ...   neg
3      Whatever you do, don't stop watching when you ...   pos
4      This is one of those movies you think that the...   neg
...                                                  ...   ...
19995  O boy, was this really bad.<br /><br />I saw t...   neg
19996  Larry Fessenden has been thrashed by most of t...   pos
19997  This may or may not be the worst movie that St...   neg
19998  I have no idea what these people were thinking...   neg
19999  "The Groove Tube" was initially shown on video...   pos

[20000 rows x 2 columns]

In [7]:
df.shape

(20000, 2)

In [9]:
df['label'][0:20]

0     pos
1     neg
2     neg
3     pos
4     neg
5     neg
6     pos
7     neg
8     neg
9     pos
10    neg
11    neg
12    neg
13    pos
14    neg
15    neg
16    pos
17    pos
18    pos
19    neg
Name: label, dtype: object

In [10]:
df['review'][0]

'The Buddy Holly Story opens on a shot of a yellow neon moon on the roof of a roller rink in 1956 Lubbock, Texas. As the credits start, the camera moves down from the moon to the parking lot, into the roller rink, past the concessions and across the rink to a small bandstand where a small band is doing their sound check. It\'s a tracking shot Welles and Scorcese would both appreciate. It cuts to Buddy Holly\'s bespectacled face peering down in rapt concentration as he grips the headphones and talks to a man putting this band on the radio. <br /><br />A young Gary Busey plays Buddy Holly and his performance is key. He has to somehow show the passion that Holly had for his music to make the film work. This is a rock and roll story without lines of coke chased with shots of heroin and a fifth of whiskey. This isn\'t about a man with several women to choose between in a sex scandalized, brood abandoned lusty tragedy. This is a film about a nice Texas boy who respected his parents and went 

In [13]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
sw = stopwords.words('english')
print(sw)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\KIIT\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [26]:
def clean_text(sample):
    sample = sample.lower()
    sample = sample.replace("<br /><br />","")
    sample = re.sub("[^a-zA-Z]+"," ",sample)
    sample = sample.split(" ")
    sample = [word for word in sample if word not in sw]
    sample = " ".join(sample)
    return sample

In [27]:
clean_text(df['review'][1])

' spoilers like evil tinkers evers chance double play combination omen iv evil seed deceased antichrist damien thorn come back terrorizing parents schoolmates neighbors finally entire world named delia york asia vieila given deserving couple yorks karen gene fay grant michael woods catholic church st francis orphanage little delia waste time making peasants felt scratching mom house party later delia almost get killed runaway truck saved devil dog named ryder going school delia takes care local bully getting big guy wet front classmates later father threatens yorks law suit head sliced self induced traffic accident delia someone never mess know good meanwhile dalia dad gene becomes big man town thinks getting elected congress champion clean air green trees crowd instead letting smog concrete boys take neighborhood eye white house bratty strange daughter delia anything gene york sudden good fortune later jo ann hearen hired delia nanny truth comes strange evil powers jo new age type rea

In [31]:
df['review'] = df['review'].apply(clean_text)

In [30]:
df['review']

0        buddy holly story opens shot yellow neon moon ...
1         spoilers like evil tinkers evers chance doubl...
2        ghost dragstrip hollow typical teens turmoil m...
3        whatever stop watching think movie hang around...
4        one movies think makers would refuse release t...
                               ...                        
19995    boy really bad saw videotape scenes soundtrack...
19996    larry fessenden thrashed comments forum well w...
19997    may may worst movie steve martin ever made cer...
19998    idea people thinking made film plot limited ac...
19999     groove tube initially shown video first video...
Name: review, Length: 20000, dtype: object

In [32]:
df

review label
0      buddy holly story opens shot yellow neon moon ...   pos
1       spoilers like evil tinkers evers chance doubl...   neg
2      ghost dragstrip hollow typical teens turmoil m...   neg
3      whatever stop watching think movie hang around...   pos
4      one movies think makers would refuse release t...   neg
...                                                  ...   ...
19995  boy really bad saw videotape scenes soundtrack...   neg
19996  larry fessenden thrashed comments forum well w...   pos
19997  may may worst movie steve martin ever made cer...   neg
19998  idea people thinking made film plot limited ac...   neg
19999   groove tube initially shown video first video...   pos

[20000 rows x 2 columns]

In [33]:
x = df['review'].values
y= df['label'].values

In [34]:
x_train = x[0:15000]
x_test = x[15000:20000]

y_train = y[0:15000]
y_test = y[15000:20000]

In [36]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

le.fit(y_train)

LabelEncoder()

In [38]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [39]:
y_train[0:20]

array([1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0])

In [49]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=1000)

In [50]:
cv.fit(x_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=1000, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [52]:
x_train = cv.transform(x_train).toarray()

In [53]:
cv.fit(x_test)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=1000, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [54]:
cv.transform(x_test).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [55]:
x_test = cv.transform(x_test).toarray()

In [59]:
from sklearn.naive_bayes import MultinomialNB

mnb = MultinomialNB()

In [60]:
mnb.fit(x_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [61]:
mnb.predict(x_test)

array([1, 1, 0, ..., 1, 1, 1])

In [62]:
mnb.score(x_test, y_test)

0.603

In [63]:
my_review = "movie was great. I enjoyed watching.. pleased.. great experience,wonderful"

In [65]:
my_review=clean_text(my_review)

In [69]:
my_review=cv.transform([my_review])

In [70]:
mnb.predict(my_review)

array([1])